# Example MergeRunConfig in YAML format

# Merge algorithm parameters
activation_threshold: 0.01 # set to null to use scalar activations for cost calculation
alpha: 1.0 # rak penalty term
iters: 100 # iterations to run. setting this to exactly the number of components can be buggy when doing ensembles, so set it to a bit less?
check_threshold: 0.05 # fraction of the range of costs to sample a merge pair from
pop_component_prob: 0 # Probability of popping a component. i recommend 0 if you're doing an ensemble anyway
filter_dead_threshold: 0.001 # Threshold for filtering dead components
module_name_filter: null  # Can be a string prefix like "model.layers.0." if you want to do only some modules
rank_cost_fn_name: const_1  # Options: const_1, const_2, log, linear

# Run configuration
model_path: wandb:goodfire/spd/runs/ioprgffh  # this can be a wandb path (then we assume it's an lm decomposition). can also be `spd_exp:<experiment_name>` to do one of the caonical runs, see the keys in `EXPERIMENT_REGISTRY`
task_name: null  # Will be inferred from model_path if its an experiment in the registry, assumed to be "lm" if none, or specify explicitly
n_batches: 10  # Ensemble size
batch_size: 64  # Batch size for processing -- number of samples for each run in the ensemble