program: <path/to/_decomposition.py>
method: grid
metric:
  name: total_loss
  goal: minimize
parameters:
  seed:
    values: [0, 1, 2, 3, 4]

command:
- ${env}
- ${interpreter}
- ${program}
- <path/to/config.yaml>